# -*- coding: utf-8 -*-
"""Processamento de imagem.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lEGycwb9XQ4FjdZ0_28uOAoP4dpulDwk
"""

!pip install pillow

import numpy as np
import matplotlib.pyplot as plt
import urllib.request
import PIL
from matplotlib import image
from matplotlib import pyplot

urllib.request.urlretrieve('https://eeweb.engineering.nyu.edu/~yao/EL5123/image/lena_gray.bmp','lena.bmp')
from PIL import Image

matriz = plt.imread('lena.bmp')

image = Image.open('lena.bmp')

image

#Cria o histograma
h = np.zeros(256)
for i in range(matriz.shape[0]):
  for j in range(matriz.shape[1]):
    h[matriz[i,j]] += 1

#Mostra o gráfico
eixo_x = list(range(256))
plt.figure(2)
plt.bar(eixo_x, h)
plt.show

data = image.imread('lena.bmp')
print(data)